FROM python:3.10

WORKDIR /app

COPY requirements.txt .

RUN apt-get update && apt-get install -y libgl1-mesa-glx
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD exec uvicorn backend.main:app --host 0.0.0.0 --port ${PORT:-8080}



